version: "3.8"

services:
  php:
    build:
      context: ./php # ここを追加\
      args:
        UID: ${UID:-1001}
        GID: ${GID:-1001}
    container_name: nomurakamotsu-php
    volumes:
      - ./wordpress:/var/www/html
      - ./php/msmtprc:/etc/msmtprc:ro
    networks:
      - wp_network

  db:
    image: mysql:5.7
    platform: linux/amd64 # 追加
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: nomura
      MYSQL_PASSWORD: 8tWJM8mz
    container_name: nomurakamotsu-mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nomurakamotsu-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8260:80"
    networks:
      - wp_network
    profiles:
      - dev

  nginx:
    image: nginx:latest
    container_name: nomurakamotsu-nginx
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html
    ports:
      - "8260:80"
    networks:
      - wp_network

networks:
  wp_network:

volumes:
  db_data:
